[package]
name = "gps-nmea"
version = "0.1.0"
authors = ["Tim Yorke <tim.yorke@embeddedscience.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "*"
nmea = "*"